Quiz moodle joneice clean
umgc/fall2024 pull request #56
Opened 2024-10-04 04:50 UTC by JoneiceB

This is my course list UI

2024-10-08 12:52 UTC, DavidWorthy commented on teamA/lib/Views/course_list.dart
> +            body: Padding(
Add a SingleChildScrollView here. While it's unlikely that anyone will have enough courses for vertical space to be an issue, better safe than sorry.

2024-10-08 12:53 UTC, DavidWorthy requested changes
Sorry for taking so long, but here is my (one) suggestion on improvement. Otherwise, this looks good.

2024-10-09 04:41 UTC, JoneiceB commented
I have updated the UI to reflect the suggestion.

2024-10-11 06:31 UTC, closed without merging

2024-10-11 06:32 UTC, DavidWorthy commented
Closed due to contributing element of this branch (the course list UI) having been added in another pull request.