quiz to moodle UI
umgc/fall2024 pull request #57
Opened 2024-10-04 04:51 UTC by JoneiceB

This is my send quiz to moodle UI

2024-10-08 14:18 UTC, DavidWorthy commented on teamA/lib/Views/send_quiz_to_moodle.dart
> +);
Color scheme can be dropped.

2024-10-08 14:19 UTC, DavidWorthy requested changes
Screen is inaccessible from the dev page, so I can't see what's there. Please adjust that.

2024-10-09 04:50 UTC, JoneiceB commented on teamA/lib/Views/send_quiz_to_moodle.dart
> +);
Done

2024-10-09 04:51 UTC, JoneiceB commented
Screen should now be accessible from dev page.

2024-10-09 16:04 UTC, DavidWorthy commented on teamA/lib/main.dart
> +        '/send_quiz_to_moodle': (contet) => QuizMoodle(),
Misspelled context.

2024-10-09 16:11 UTC, DavidWorthy commented on teamA/lib/Views/send_quiz_to_moodle.dart
> +            TextField(
Course name should really be a dropdown with its contents taken from the course list, but that can be handled as part of the BL.

2024-10-10 23:57 UTC, JoneiceB commented
Updated the 'send quiz to moodle' UI to have the dropdown button for course name. Also updated the 'course list' UI as well.

2024-10-11 06:31 UTC, DavidWorthy approved these changes
All good. Part of the reason why I didn't review the other branch after the changes is that there were some... oddities in some of additional files. Now that the course list is also implemented here, I can close both branches.

2024-10-11 06:31 UTC, merged